# Generated by Django 3.1.5 on 2021-01-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='one',
            name='roll',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='two',
            name='age',
            field=models.IntegerField(),
        ),
    ]
