# Generated by Django 3.1.4 on 2021-01-22 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='one',
        ),
    ]
