# Generated by Django 3.1.4 on 2021-01-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210122_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='one',
            name='city',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
